---
abstract: 'Random terrain generation via the Diamond Square algorithm'
author:
  - "Curtis \"Ovid\" Poe <ovid@cpan.org>"
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-Terrain-DiamondSquare
requires:
  Exporter: 0
  List::Util: 0
  POSIX: 0
  base: 0
  constant: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/Ovid/Games-Terrain-DiamondSquare.git
version: 0.02
